
--- 
after_success: 
  - "mvn clean test jacoco:report coveralls:report"
before_install: 
  - "cd sandwich-shop-manager"
cache: 
  directories: 
    - $HOME/.m2
dist: trusty
group: edge
jdk: openjdk8
language: java
script: 
  - "mvn clean install"
sudo: required
